server:
  port: 8004

spring:
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

#服务别名 --- 注册zookeeper到注册中心名称

  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 218.244.149.43:2181


