server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    客户端向服务端发送心跳频率
#    lease-renewal-interval-in-seconds: 1
#    多少时间没收到心跳之后，服务端删除注册服务信息
#    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.wduac.springcloud.entities

